package DCT.common;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, CLIENT_ID, RESET_USER_LIST,
    SYNC_CLIENT, CREATE_ROOM, JOIN_ROOM, GET_ROOMS,
    READY, PHASE, CHARACTER, TURN, MOVE, CELL, GRID, GRID_RESET, ROLL, FLIP, MUTE, UNMUTE, PM, EXPORT
}
