package server;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, CLEAR_PLAYERS, SYNC_DIRECTION, SYNC_POSITION, CREATE_ROOM, JOIN_ROOM, GET_ROOMS,
    SYNC_CHAIR, SYNC_TICKET, SYNC_GAME_SIZE, PICKUP_TICKET, SET_COUNTDOWN, TOGGLE_LOCK, UPDATE_COLLECTOR, KICK_PLAYER
}