package LifeForLife.common;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, CLIENT_ID, RESET_USER_LIST, 
    SYNC_CLIENT, CREATE_ROOM, JOIN_ROOM, GET_ROOMS,
    READY, LIFE, START, SYNC_POSITION_ROTATION, SHOOT, SYNC_PROJECTILE, PHASE, TIME
}
